### ISSUE TITLE
Key combinations sometimes do not work in Ubuntu 21.04

### ISSUE THREAD

**Issue by drnguyenn** [iberianpig/fusuma-plugin-keypress#5]
Hi. I have successfully installed `fusuma` along with `fusuma-plugin-keypress` on my Ubuntu 21.04 by following the instruction in the documentation. They work pretty well on many applications, however, when I tried with the Terminal, the key combinations seem not to work. I have tried executing this command in my Terminal
```
$ fusuma-sendkey 'LEFTCTRL+T'
```
and was expecting that a new tab was opened, but I only received the letter `t` printed out:
```
$ t
```
Can you please tell me what should I do to work around this? Thanks a lot.

**Comment by iberianpig** [comment]
What terminal are you using? Will it be reproduced in other terminals?

**Comment by drnguyenn** [comment]
> What terminal are you using? Will it be reproduced in other terminals?

I'm using just the default Terminal and I have no other Terminal installed on my computer.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/38097720/129369084-40902d82-7590-4284-8e62-5a1b564d2738.gif)

**Comment by iberianpig** [comment]
I think the correct shortcut key is `Ctrl+Shift+T` for opening a new tab on gnome-terminal.

[![Image from Gyazo](https://i.gyazo.com/df9a4d3be9371fae397e135631c20900.gif)](https://gyazo.com/df9a4d3be9371fae397e135631c20900)

**Comment by iberianpig** [comment]
Also, this repository is fusuma-plugin-keypress, not a place to post issues of fusuma-plugin-sendkey :sweat_smile:

**Comment by drnguyenn** [comment]
> Also, this repository is fusuma-plugin-keypress, not a place to post issues of fusuma-plugin-sendkey

Oh no I did not realize that I have created the issue in the wrong place. Sorry :sweat_smile: I will open a new one in your `fusuma-plugin-sendkey` repository.
